sudo: required
language: r
cache: packages
cran: https://cran.rstudio.com/
env:
  global:
    secure: WNm/3nk5Gz4VVP/AsH8PWyF8bv2VETxQ2GUwCqIn/GvA/wMjxre46A++1pv6sAcFX3CEaOPYAdh1Le1Oj7B8M03j7yQ4alaEjqNTGVhRQQaDSceXCHEiyPLYOHua7GAGVwslarWhF7t7ALGZ1ZKmFTnJJQscNxRiSyL8l7mnupeU/3S/j76NW15C3pCMqotbo8bc1qSVmV5MjLBZAL3x2FzRei3rrgaG23joTkPstXVJCXfZg99MWTzKyDd54n03aARLNhQbBvZll8p5IjmfxPGAPgXxm5S7MZvMSwrBg6zcsBds+SwRsBpDt4NOhXuPG+mrgKRy5lsK8EOkH6Huk2BiByTH9xRxKcPvH7+q02yNEAVThDpnrh0pQkNm0neTp8ieujxiFga6USw3ASVR2GmvosDlD1x2XzZcvusK+CqbfDlJ+SGganE2ncX1a8fJt76DC2E9hnuXNIDLAYB1XbWaFHnslbKMjBcfVlIBdz5FBnSB8gjK1uxIA2ULz7Wl0q6v90tB3FM85VPRQnAaNvpXkJw1KuGNWD/Yi6UFRBG8Vxl6dfOIiqTbTMbc6tPB0zC7hBK2v6DipMzYPQvcR34pXCvasY51fK5q4cLs0XgJUKx6XcKyFcq9sG2nYjBUteUZbhyX258atUErkmM8PxWOrmkiDfedE+nA9HAGGnE=
matrix:
  include:
  - os: linux
    dist: trusty
    r: 3.3.0
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    r_packages:
    - rgdal
  - os: linux
    dist: trusty
    r: oldrel
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    r_packages:
    - rgdal
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
    r_github_packages:
    - jimhester/lintr
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    r_packages:
    - rgdal
    after_success:
    - Rscript -e 'covr::coveralls(package_coverage(type = "all", quiet = FALSE)))'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: trusty
    r: devel
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    r_packages:
    - rgdal
    - devtools
    - udunits2
  - os: osx
    osx_image: xcode9.2
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    before_script:
    - Rscript -e "install.packages('rgdal', type = 'source')"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    recipients:
    - alex.chubaty@gamil.com
    - eliotmcintire@gmail.com
    - jean.d.marchal@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
  - master
  - development
  - testing
  - prepInputs
